

InstallerType: null
UpgradeBehavior: install
ReleaseDate: 2026-10-04
InstallerSha256: dc710c33de0448bfb0390c95c9e5ee292a79eb64e6469c6fbd642393faaa9cc7
InstallerUrl: https://github.com/yubin1-0-4-6/AI-Radar/releases/download/v0.1.1/AI.Radar_0.1.1_x64-setup.exe
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
Installers:
  - Architecture: x64
    InstallerType: null
    Scope: user